### ISSUE TITLE
Can I buy this board

### ISSUE THREAD

**Issue by nsmith1024** [electroniceel/vocore2-breakout#1]
Hello,

Im wondering if its possible for me to buy this board completely soldered with all the part on it.

Please let me know I want to buy some of them

Thanks

**Comment by electroniceel** [comment]
Thanks for your interest. 

Unfortunately it is not easy to make a business out of selling boards like these. Also I don't want to deal with registering a company and all the bureaucracy like taxes that comes with it. And selling goods without that is illegal here.

Several vendors made PCB-Assembly services available for prototype and small quantity production recently. One such example is JLCPCB in China, the other AISLER in Germany. I have used the PCBA service from JLCPCB and it works well. You could have everything populated there except the Vocore itself. But that isn't too hard do solder onto the board when using 1.27mm pitch pin headers.
